version: '3.8'

services:
  # 🚀 Claude Power - Servicio principal
  claude-power:
    build: .
    container_name: claude-power
    image: claude-power/slash-commands:latest
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - CLAUDE_POWER_ENV=docker
    volumes:
      # Montar configuración de usuario
      - ~/.claude:/home/claude/.claude:rw
      # Montar directorio de trabajo actual (para development)
      - ./:/workspace:rw
    working_dir: /workspace
    ports:
      - "3000:3000"
    networks:
      - claude-power-net
    healthcheck:
      test: ["CMD", "node", "/app/index.js", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.claude-power.service=main"
      - "com.claude-power.version=1.0.0"

  # 🧪 Servicio para testing y desarrollo
  claude-power-dev:
    build:
      context: .
      target: dev
    container_name: claude-power-dev
    image: claude-power/slash-commands:dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - CLAUDE_POWER_ENV=development
    volumes:
      - ./:/app:rw
      - ~/.claude:/home/claude/.claude:rw
      - node_modules:/app/node_modules
    working_dir: /app
    ports:
      - "3001:3000"
      - "9229:9229"  # Puerto para debugging
    networks:
      - claude-power-net
    command: ["npm", "run", "dev"]
    profiles:
      - development
    labels:
      - "com.claude-power.service=development"

# Volúmenes
volumes:
  node_modules:
    driver: local

# Red personalizada
networks:
  claude-power-net:
    driver: bridge
    name: claude-power-network 